apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  labels:
    environment: staging
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce