apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: app-pv
  labels:
    environment: dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data