apiVersion: apps/v1
kind: Deployment 
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: flask-app 
  template:
    metadata: 
      Labels: 
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: chrispined/pythonApp:py-app-1.0
          ports:
            - containerPort: 5000
          env:
            - name: PROMETHEUS_MONITORING_ENABLED
              value: "true"

--- 
apiVersion: v1 
kind: Service 
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 5000
  