apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app-deploy.fullname" . }}
  labels:
    {{- include "flask-app-deploy.labels" . | nindent 4 }}

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flask-app-deploy.selectorLabels" . | nindent 4 }}
