apiVersion: apps/v1
kind: Deployment 
metadata:
  namespace: backend
  name: backend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: back
          image: nginx
          ports:
            - containerPort: 80