apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend-app
  namespace: frontend 
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: front 
  template:
    metadata:
      labels: 
        app: front
    spec:
      containers:
        - name: front
          image: nginx
          ports:
            - containerPort: 80