apiVersion: v1
kind: ConfigMap 
metadata:
  name: app-config
  namespace: dev 
data:
  APP_ENV: "development"
  LOG_LEVEL: "debug"
  DATABASE_URL: "postgres://dev_user:dev_password@dev-db:5432/dev_db"
