apiVersion: apps/v1
kind: Deployment 
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
          - "--config.file=/etc/prometheus/prometheus.yaml"
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: config-name
            mountPath: /etc/prometheus
      volumes: 
        - name: config-name
          configMap:
            - name: prometheus-config

---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yaml: |
    global: 
      scrape_interval = 15s
    
    scrape_configs:
      - job_name: 'kubernetes'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep 
            regex: myapp