apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: false
  allowPriviledgeEscalation: false
  requiredDropCapabilities: 
   - ALL
  volumes:
   - 'configMap'
   - 'secret'
  runAsUser:
   rule: 'MustRunAsNonRoot'
  selinux:
   rule: 'RunAsAny'
