apiVersion: v1 
kind: Service 
metadata:
  name: app-service
  namespace: production
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
