apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: default
  name: allow-specific-ingress
spec:
  podSelector:
    matchLabels:
      app: myapp
  policyTypes:
    - Ingress 
  ingress: 
  - from:
      - namespaceSelector:
          matchLabels:
            access: allowed 
      - podSelector:
          matchLabels:
            role: frontend
