spec:
  replicas: 1
  template:
    spec:
     containers:
       - name: flask-app
         resources:
           requests:
             memory: "64Mi"
             cpu: "100m"
           limits:
             memory: "128Mi"
             cpu: "250m"