apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: production-app-ingress
spec:
  rules:
  - host: production.com.example
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: production-app-service
            port: 
              number: 80
