apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: stage-app-ingress
spec:
  rules: 
    - host: stage.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: stage-app-service
                port:
                  number: 80